version: "3"
services:
  chrome:
    image: seleniarm/node-chromium:4.2.2-20220620
    shm_size: 2gb
    depends_on:
      - selenium-hub
    ports:
      # For debugging via remote desktop
      - "5900:5900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: seleniarm/hub:4.2.2-20220620
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
